### ISSUE TITLE
Assignment: Create app module

### ISSUE THREAD

**Issue by khai93** [khai93/godtest#2]
The app module has the responsibility to manage apps, just **edit**, **add**, **delete**;

An app should have a **name**, **url**, **description**.

Danny should be able to create the "vex" app with the url "vex.dev", description "god application".
Danny wants to edit the description to "g" but descriptions can't be smaller than 5 length.
Danny gets frustrated and tries to delete it.
The End.

LOG EVERYTHING

FOLLOW THE S IN SOLID.

TRY TO FOLLOW THE CODE STYLE OF EXISTING CODE.

**Comment by remote-event** [comment]
PLEASE ASSIGN THIS ISSUE TO ME **TEACHER**!!!
